# -*- coding: utf-8 -*-
"""기존 수요 예측_AI 예측_에러율 비교.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1WyUTkrFnwCYBwQZpew2hptNBgaPmXt
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. 데이터 로딩 및 전처리
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_excel("/content/drive/MyDrive/파주지사_A.I예측추가(2022~2025).xlsx")

# 2. 열수요실적이 0이 아닌 행만 사용
df = df[df['열수요실적'] != 0].copy()
# 3. 오차율 계산
df['오차율_열수요예측'] = ((df['열수요예측'] - df['열수요실적']).abs() / df['열수요실적']) * 100
df['오차율_AI'] = ((df['A.I'] - df['열수요실적']).abs() / df['열수요실적']) * 100

# 4. 일자 형식 정리
df['일자'] = pd.to_datetime(df['일자'])

# ▶ 월 컬럼 추가
df['월'] = df['일자'].dt.month

# 5. 월별 평균 오차율 계산
monthly_error = df.groupby('월')[['오차율_열수요예측', '오차율_AI']].mean()

# 6. 시각화
plt.figure(figsize=(12, 6))
plt.plot(monthly_error.index, monthly_error['오차율_열수요예측'], marker='o', label='Thermal demand forecast error rate')
plt.plot(monthly_error.index, monthly_error['오차율_AI'], marker='o', label='AI forecast error rate')
plt.title('Monthly average error rate (%)')
plt.xlabel('Month')
plt.ylabel('Error rate (%)')
plt.xticks(range(1, 13))  # x축을 1~12월로 고정
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# 7. 전체 평균 오차율 출력
print("열수요예측 전체 평균 오차율: {:.2f}%".format(df['오차율_열수요예측'].mean()))
print("AI 예측 전체 평균 오차율: {:.2f}%".format(df['오차율_AI'].mean()))

# 8. 월별 평균 오차율 테이블 출력
print("\n[월별 평균 오차율 테이블]")
print(monthly_error.round(2))

"""🔍 그래프 해석
1. x축: 1월 ~ 12월
한 해의 월(month) 단위로 나뉘어 있음

2022~2025년 전체 데이터를 합쳐서 각 월의 평균 오차율을 계산했기 때문에 전체적인 월별 경향을 보여줍니다.

2. y축: 오차율 (%)
예측값이 실제 열수요 실적에서 얼마나 벗어났는지를 백분율(%)로 표시

값이 낮을수록 예측이 정확합니다.

3. 파란 선 (Thermal Forecast Error Rate)
기존 열수요예측 모델의 오차율

일반적으로 기상 데이터 기반 선형 회귀나 수식 기반 예측이 포함됩니다

몇몇 달(예: 여름철 혹은 환절기)에서 오차율이 상대적으로 높게 나타날 수 있음

4. 주황 선 (AI Forecast Error Rate)
AI 기반 예측 모델의 오차율 (예: LSTM, RNN, 딥러닝 모델 등)

일반적으로 더 많은 데이터 패턴을 학습하므로 변동성 높은 구간에서도 상대적으로 안정된 정확도를 보입니다

5. 두 선의 비교
AI 오차율 선이 항상 아래에 있다면: → AI 예측이 더 정확

두 선이 교차하거나, 일부 달에서 열수요예측이 더 정확하면: → 월별로 성능 차이가 있음

📊 종합 분석 예시 (가정)
월	열수요예측 오차율	AI 오차율	해석
1월	31.1%	24.4%	난방 수요가 높은 겨울, AI가 더 정확
6월	27.9%	26.2%	수요 예측이 까다로운 환절기, 두 모델 비슷
10월	28.0%	23.0%	열 공급 변동이 많은 가을, AI 우위

✅ 요약 정리
AI 예측 모델이 대부분의 월에서 기존 모델보다 더 낮은 오차율을 보여줌

특히 수요가 급격히 바뀌는 시기(환절기, 겨울철)에 AI의 장점이 두드러짐

전체적으로 볼 때 AI 기반 예측 모델이 기존 방식보다 더 정밀한 예측을 수행하고 있음


"""
